version: "3.8"
services:
  frontend:
    container_name: goserver
    image: alexandermca/goweb:2.3
    ports:
      - "8080:8080"
    environment:
      - GOPORT=8080
      - NODEPORTPY=3000
      - NODEPORTJS=3080
    volumes:
      - ./Go:/App/
  webpy:
    container_name: nodeserverpy
    image: alexandermca/nodewebpy:2.3
    ports:
      - "3000:3000"
    environment:
      - NODEPORTPY=3000
    volumes:
      - ./NodePY:/App/
      - /App/node_modules
  webjs:
    container_name: nodeserverjs
    image: alexandermca/nodewebjs:2.3
    ports:
      - "3000:3000"
    environment:
      - NODEPORTPY=3000
    volumes:
      - ./NodeJS:/App/
      - /App/node_modules


        
