version: "3"
services:
  frontend:
    container_name: goserver
    image: alexandermca/goweb:2.6
    ports:
      - "8080:8080"
    environment:
      - GOIP=182.18.7.9
      - GOPORT=8080
      - NODEIPPY=182.18.7.7
      - NODEPORTPY=3000
      - NODEIPJS=182.18.7.5
      - NODEPORTJS=3080
    volumes:
      - ./GoS:/App/
    networks:
      testing_net:
            ipv4_address: 182.18.7.9
    depends_on:
      - backend
      - backend2
  backend:
    container_name: nodeserverpy
    image: alexandermca/nodewebpy:2.6
    ports:
      - "3000:3000"
    environment:
      - NODEIP=182.18.7.7
      - NODEPORT=3000
    volumes:
      - ./NodePY:/App/
      - /App/node_modules
    networks:
      testing_net:
            ipv4_address: 182.18.7.7
  backend2:
    container_name: nodeserverjs
    image: alexandermca/nodewebjs:2.6
    ports:
      - "3080:3080"
    environment:
      - NODEIPJS=182.18.7.5
      - NODEPORTJS=3080
    volumes:
      - ./NodeJS:/App/
      - /App/node_modules
    networks:
      testing_net:
            ipv4_address: 182.18.7.5

networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 182.18.7.0/24


        
